ALTER TABLE users 
ADD COLUMN cover_image VARCHAR(200) NULL,
ADD COLUMN facebook VARCHAR(200) NULL,
ADD COLUMN instagram VARCHAR(200) NULL,
ADD COLUMN tiktok VARCHAR(200) NULL,
ADD COLUMN dribble VARCHAR(200) NULL;
