CREATE TABLE events (
	id serial PRIMARY KEY,
	"_id" varchar(100) DEFAULT NULL,
	"StartDate" VARCHAR ( 40 ) DEFAULT NULL,	
	"Description" text,	
	"Headline" varchar(255) DEFAULT NULL,
	"Name" varchar(100) DEFAULT NULL,	
	"Summary" text,
	"StartTime" varchar(20) DEFAULT NULL,
	"CreatedDate" varchar(40) DEFAULT NULL,
	"Slug" varchar(100) DEFAULT NULL,
	"CreatedBy" varchar(100) DEFAULT NULL,
	"ModifiedDate" varchar(40) DEFAULT NULL,
	"Address" varchar(200) DEFAULT NULL,
	"BGImage" varchar(400) DEFAULT NULL,
	"Venue" varchar(100) DEFAULT NULL,	
	"mainColor1" varchar(30) DEFAULT NULL,
	"mainColor2" varchar(30) DEFAULT NULL,
	"textColor1" varchar(30) DEFAULT NULL,
	"textColor2" varchar(30) DEFAULT NULL,
	"Vibes" text,
	"Sponsors" text,
	"Limit" INT DEFAULT NULL,
	"Artists" text,
	"Attendees" text,
	"Paid" BOOLEAN DEFAULT NULL,
	"Hosts" text,
	"Template" varchar(50) DEFAULT NULL,	
	"EventPic" varchar(400) DEFAULT NULL,
	"state" varchar(50) DEFAULT NULL,
	"opencall" BOOLEAN DEFAULT NULL,
	"Artsubmit" text,
	"bgvideo" varchar(100) DEFAULT NULL,
	"Price" INT DEFAULT NULL,
	"Mode" varchar(50) DEFAULT NULL,
	"Event_venue" varchar(100) DEFAULT NULL,
		
	"createdAt" TIMESTAMP NOT NULL,        
	"updatedAt" TIMESTAMP NOT NULL  
);
