/**
 * Policy Mappings
 * (sails.config.policies)
 *
 * Policies are simple functions which run **before** your actions.
 *
 * For more information on configuring policies, check out:
 * https://sailsjs.com/docs/concepts/policies
 */

module.exports.policies = {
  /***************************************************************************
   *                                                                          *
   * Default policy for all controllers and actions, unless overridden.       *
   * (`true` allows public access)                                            *
   *                                                                          *
   ***************************************************************************/

  // '*': true,
  "vibes/get": ["isLoggedIn"],
  "user/vibes/update": ["isLoggedIn"],
  "user/vibes/get": ["isLoggedIn"],
  "interests/get": ["isLoggedIn"],
  "user/interests/update": ["isLoggedIn"],
  "user/interests/get": ["isLoggedIn"],
  "user/dashboard-feeds": ["isLoggedIn"],
  "user/follow-community": ["isLoggedIn"],
  "user/communities/get": ["isLoggedIn"],
  "user/communities/drops": ["isLoggedIn"],
  "user/follow-artist": ["isLoggedIn"],
  "user/arts/pin-unpin": ["isLoggedIn"],
  "user/art-collections/pin-unpin": ["isLoggedIn"],
  "user/arts/pinned/change-privacy": ["isLoggedIn"],
  "user/arts/pinned/get": ["isLoggedIn"],
  "user/addresses/get": ["isLoggedIn"],
  "user/addresses/create": ["isLoggedIn"],
  "user/addresses/update": ["isLoggedIn"],
  "user/addresses/delete": ["isLoggedIn"],
  "user/addresses/select-default": ["isLoggedIn"],
  "user/edit/profile": ["isLoggedIn"],
  "user/edit/personal-info": ["isLoggedIn"],
  "user/edit/social-login": ["isLoggedIn"],
  "user/edit/become-artist": ["isLoggedIn"],
  "communities/get": ["isLoggedIn"],
  "arts/get-one": ["isLoggedIn"],
  "arts/get": ["isLoggedIn"],
  "user/art-collections/create": ["isLoggedIn"],
  "user/art-collections/update": ["isLoggedIn"],
  "user/art-collections/delete": ["isLoggedIn"],
  "user/art-collections/delete-art": ["isLoggedIn"],
  "user/art-collections/get": ["isLoggedIn"], 
  "user/art-collections/get-one": ["isLoggedIn"],
  "user/art-collections/detail/get-one": ["isLoggedIn"],
  "user/collections/create": ["isLoggedIn"],
  "user/collections/update": ["isLoggedIn"],
  "user/collections/delete": ["isLoggedIn"],
  "user/collections/get": ["isLoggedIn"],
  "user/arts/create": ["isLoggedIn","isArtist"],
  "user/arts/update": ["isLoggedIn","isArtist"],
  "user/arts/delete": ["isLoggedIn"],
  "user/arts/support": ["isLoggedIn"],
  "artists/get": ["isLoggedIn"],
  "artists/get-one": ["isLoggedIn"],
  "arts/related": ["isLoggedIn"],
  "artists/following": ["isLoggedIn"],
  "artists/followers": ["isLoggedIn"],
  "user/followers/delete": ["isLoggedIn"],
  "user/orders/create": ["isLoggedIn"],
  "user/orders/get": ["isLoggedIn"],
  "user/orders/get-one": ["isLoggedIn"],
  "user/orders/payment-intents/create": ["isLoggedIn"],
  "user/orders/change-privacy": ["isLoggedIn"],
  "user/cards/add": ["isLoggedIn"],
  "user/cards/get": ["isLoggedIn"],
  "user/cards/delete": ["isLoggedIn"],
  "user/cards/select-default": ["isLoggedIn"],
  "user/transactions/get": ["isLoggedIn"],
  "user/comments/create": ["isLoggedIn"],
  "user/comments/update": ["isLoggedIn"],
  "user/comments/delete": ["isLoggedIn"],
  "user/comments/get": ["isLoggedIn"],
  "user/comments/like-unlike": ["isLoggedIn"],
  "user/search/items": ["isLoggedIn"],
  "user/sales/get": ["isLoggedIn"],
  "user/sales/orders/get": ["isLoggedIn"],
  "user/sales/orders/get-one": ["isLoggedIn"],
  "user/sales/orders/change-status": ["isLoggedIn"],
  "user/vibes/arts": ["isLoggedIn"],
  "user/device-tokens/save": ["isLoggedIn"],
  "user/device-tokens/delete": ["isLoggedIn"],
  "user/stripe/accounts/create": ["isLoggedIn"],
  "user/stripe/accounts/get": ["isLoggedIn"],
  "user/stripe/accounts/delete": ["isLoggedIn"],
  "user/withdrawals/request": ["isLoggedIn","isArtist"],
  "user/notifications/get": ["isLoggedIn"],
  "user/notifications/mark-as-read": ["isLoggedIn"],
  "user/notifications/unread-count": ["isLoggedIn"],
  "user/events/get": ["isLoggedIn"],
  "user/order-arts/get": ["isLoggedIn"],
  "user/addresses/mark-picking-point": ["isLoggedIn"],
  "user/orders/shipment/calculate-charges": ["isLoggedIn"],
  "user/communities/data": ["isLoggedIn"],
  "user/events/get-one": ["isLoggedIn"],
  "user/sales/orders/dispatch": ["isLoggedIn"],
  "user/comments/replies": ["isLoggedIn"],
  "user/communities/forums/create": ["isLoggedIn"],
  "user/communities/forums/get": ["isLoggedIn"],
  "user/communities/edit": ["isLoggedIn"],
  "user/communities/get-one": ["isLoggedIn"],


  //////Admin Policies
  "admin/users/get": ["isLoggedIn","isAdmin"],
  "admin/users/get-one": ["isLoggedIn","isAdmin"],
  "admin/users/create": ["isLoggedIn","isAdmin"],
  "admin/users/update": ["isLoggedIn","isAdmin"],
  "admin/users/change-status": ["isLoggedIn","isAdmin"],
  "admin/interests/get": ["isLoggedIn","isAdmin"],
  "admin/interests/get-one": ["isLoggedIn","isAdmin"],
  "admin/interests/create": ["isLoggedIn","isAdmin"],
  "admin/interests/edit": ["isLoggedIn","isAdmin"],
  "admin/interests/delete": ["isLoggedIn", "isAdmin"],
  "admin/vibes/get": ["isLoggedIn","isAdmin"],
  "admin/vibes/get-one": ["isLoggedIn","isAdmin"],
  "admin/vibes/create": ["isLoggedIn","isAdmin"],
  "admin/vibes/edit": ["isLoggedIn","isAdmin"],
  "admin/vibes/delete": ["isLoggedIn", "isAdmin"],
  "admin/arts/get": ["isLoggedIn","isAdmin"],
  "admin/arts/get-one": ["isLoggedIn","isAdmin"],
  "admin/arts/create": ["isLoggedIn","isAdmin"],
  "admin/arts/edit": ["isLoggedIn","isAdmin"],
  "admin/arts/delete": ["isLoggedIn", "isAdmin"],
  "admin/art-collections/get": ["isLoggedIn","isAdmin"],
  "admin/art-collections/get-one": ["isLoggedIn", "isAdmin"],
  "admin/sales/get": ["isLoggedIn","isAdmin"],
  "admin/sales/get-one": ["isLoggedIn", "isAdmin"],
  "admin/purchases/get": ["isLoggedIn","isAdmin"],
  "admin/purchases/get-one": ["isLoggedIn", "isAdmin"],
  "admin/communities/get": ["isLoggedIn","isAdmin"],
  "admin/communities/get-one": ["isLoggedIn","isAdmin"],
  "admin/communities/create": ["isLoggedIn","isAdmin"],
  "admin/communities/edit": ["isLoggedIn","isAdmin"],
  "admin/communities/delete": ["isLoggedIn", "isAdmin"],
  "admin/withdrawal-requests/get": ["isLoggedIn", "isAdmin"],
  "admin/withdrawal-requests/approve": ["isLoggedIn", "isAdmin"],
  "admin/withdrawal-requests/reject": ["isLoggedIn", "isAdmin"],
  "admin/events/get": ["isLoggedIn","isAdmin"],
  "admin/events/get-one": ["isLoggedIn","isAdmin"],
};
